version: '3'
services:
  client:
    container_name: client
    restart: always
    build:
      context: ./
      dockerfile: ./Dockerfile
    expose:
      - "3000:3000"
    networks:
      - "blog"
networks:
  blog:
    driver: bridge
